updating docs with examples
data-8/Gofer-Grader pull request #7
Opened 2018-06-18 23:06 UTC by choldgraf

I wanted to wrap my head around `okgrade`, and figured the best way to do so would be to write some docs :-)

This PR:

* Adds some user-friendly sample Jupyter Notebooks in an `examples/` folder
* Adds more language in usage for the two main use-cases of `okgrade` (interactive feedback and auto-grading)
* Cleans up the language here and there for organization / clarity
* Adds Binder links so people can interact

2018-06-22 21:54 UTC, yuvipanda requested changes
w00t, thank you for taking the effort to do this :)

I'm continuing to break everything, so will ping here again once all the breaking has stabilized a bit :)

2018-06-22 21:54 UTC, yuvipanda commented on docs/index.md
> +It is not dependent on any other grading packages and tools (such as `okpy` or
I'm unsure what using these 'alongside' means!

2018-06-22 21:54 UTC, yuvipanda commented on docs/index.md
> +1. Jupyter Notebooks in which students have done their work.
We also support plain .py files.

2018-06-23 00:15 UTC, choldgraf commented on docs/index.md
> +1. Jupyter Notebooks in which students have done their work.
good to know, didn't realize that :-D

2018-06-23 00:15 UTC, choldgraf commented
cool - lemme know when it's time for me to take another crack at this!

2018-08-11 21:26 UTC, choldgraf commented
Gonna close this since GMM has changed quite a bit and I'm not sure yuvi wants to do the code reviews for this :-)

2018-08-11 21:26 UTC, closed without merging